//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.19 at 04:10:08 PM IST 
//


package com.migration.soapservice.entity;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Applicant Bureau Information
 * 
 * <p>Java class for ApplicantBureauInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ApplicantBureauInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BureauInfo" type="{http://migration.com/soapservice/entity}ApplicantBureauData" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ApplicantBureauInfo", propOrder = {
    "bureauInfo"
})
public class ApplicantBureauInfo {

    @XmlElement(name = "BureauInfo")
    protected ApplicantBureauData bureauInfo;

    /**
     * Gets the value of the bureauInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ApplicantBureauData }
     *     
     */
    public ApplicantBureauData getBureauInfo() {
        return bureauInfo;
    }

    /**
     * Sets the value of the bureauInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApplicantBureauData }
     *     
     */
    public void setBureauInfo(ApplicantBureauData value) {
        this.bureauInfo = value;
    }

}
