//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.19 at 04:10:08 PM IST 
//


package com.migration.soapservice.entity;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Applicant information
 * 
 * <p>Java class for ApplicantInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ApplicantInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AppAge" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;totalDigits value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="MthsAtCurrentJob" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;totalDigits value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="MthsAtCurrentRes" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;totalDigits value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ApplicantEducLvl" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;totalDigits value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="HousingType">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;totalDigits value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ExistingAcctFlag" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="MultipleAppFlag" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="AddrDiscrepancyFlag" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="RedFlagAlert" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="IdentityAlert" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ActiveMilitaryAlert" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="AppSSNInvalid" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ConsumerStatement" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="OFACAlert" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="RetiredFlag" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="EmployedFlag" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="NbrOfOpenTaxLiens" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;totalDigits value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="DecisionCBName">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="State">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ApplicantBureauInfo" type="{http://migration.com/soapservice/entity}ApplicantBureauInfo"/>
 *         &lt;element name="PrevAppDebtOfApplicant" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="8"/>
 *               &lt;fractionDigits value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="DebtOfApplicant" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="8"/>
 *               &lt;fractionDigits value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PrevAppMonthlyIncome" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="8"/>
 *               &lt;fractionDigits value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="AppMonthlyIncome" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="8"/>
 *               &lt;fractionDigits value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="NameDiscrepancyFlag" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PhoneNumberDiscrepancyFlag" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="SSNDiscrepancyFlag" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="CVIscore" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;totalDigits value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ApplicantInfo", propOrder = {
    "appAge",
    "mthsAtCurrentJob",
    "mthsAtCurrentRes",
    "applicantEducLvl",
    "housingType",
    "existingAcctFlag",
    "multipleAppFlag",
    "addrDiscrepancyFlag",
    "redFlagAlert",
    "identityAlert",
    "activeMilitaryAlert",
    "appSSNInvalid",
    "consumerStatement",
    "ofacAlert",
    "retiredFlag",
    "employedFlag",
    "nbrOfOpenTaxLiens",
    "decisionCBName",
    "state",
    "applicantBureauInfo",
    "prevAppDebtOfApplicant",
    "debtOfApplicant",
    "prevAppMonthlyIncome",
    "appMonthlyIncome",
    "nameDiscrepancyFlag",
    "phoneNumberDiscrepancyFlag",
    "ssnDiscrepancyFlag",
    "cvIscore"
})
public class ApplicantInfo {

    @XmlElement(name = "AppAge")
    protected BigInteger appAge;
    @XmlElement(name = "MthsAtCurrentJob")
    protected BigInteger mthsAtCurrentJob;
    @XmlElement(name = "MthsAtCurrentRes")
    protected BigInteger mthsAtCurrentRes;
    @XmlElement(name = "ApplicantEducLvl")
    protected BigInteger applicantEducLvl;
    @XmlElement(name = "HousingType", required = true)
    protected BigInteger housingType;
    @XmlElement(name = "ExistingAcctFlag")
    protected String existingAcctFlag;
    @XmlElement(name = "MultipleAppFlag")
    protected String multipleAppFlag;
    @XmlElement(name = "AddrDiscrepancyFlag")
    protected String addrDiscrepancyFlag;
    @XmlElement(name = "RedFlagAlert")
    protected String redFlagAlert;
    @XmlElement(name = "IdentityAlert")
    protected String identityAlert;
    @XmlElement(name = "ActiveMilitaryAlert")
    protected String activeMilitaryAlert;
    @XmlElement(name = "AppSSNInvalid")
    protected String appSSNInvalid;
    @XmlElement(name = "ConsumerStatement")
    protected String consumerStatement;
    @XmlElement(name = "OFACAlert")
    protected String ofacAlert;
    @XmlElement(name = "RetiredFlag")
    protected String retiredFlag;
    @XmlElement(name = "EmployedFlag")
    protected String employedFlag;
    @XmlElement(name = "NbrOfOpenTaxLiens")
    protected BigInteger nbrOfOpenTaxLiens;
    @XmlElement(name = "DecisionCBName", required = true)
    protected String decisionCBName;
    @XmlElement(name = "State", required = true)
    protected String state;
    @XmlElement(name = "ApplicantBureauInfo", required = true)
    protected ApplicantBureauInfo applicantBureauInfo;
    @XmlElement(name = "PrevAppDebtOfApplicant")
    protected BigDecimal prevAppDebtOfApplicant;
    @XmlElement(name = "DebtOfApplicant")
    protected BigDecimal debtOfApplicant;
    @XmlElement(name = "PrevAppMonthlyIncome")
    protected BigDecimal prevAppMonthlyIncome;
    @XmlElement(name = "AppMonthlyIncome")
    protected BigDecimal appMonthlyIncome;
    @XmlElement(name = "NameDiscrepancyFlag")
    protected String nameDiscrepancyFlag;
    @XmlElement(name = "PhoneNumberDiscrepancyFlag")
    protected String phoneNumberDiscrepancyFlag;
    @XmlElement(name = "SSNDiscrepancyFlag")
    protected String ssnDiscrepancyFlag;
    @XmlElement(name = "CVIscore")
    protected BigInteger cvIscore;

    /**
     * Gets the value of the appAge property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAppAge() {
        return appAge;
    }

    /**
     * Sets the value of the appAge property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAppAge(BigInteger value) {
        this.appAge = value;
    }

    /**
     * Gets the value of the mthsAtCurrentJob property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMthsAtCurrentJob() {
        return mthsAtCurrentJob;
    }

    /**
     * Sets the value of the mthsAtCurrentJob property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMthsAtCurrentJob(BigInteger value) {
        this.mthsAtCurrentJob = value;
    }

    /**
     * Gets the value of the mthsAtCurrentRes property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMthsAtCurrentRes() {
        return mthsAtCurrentRes;
    }

    /**
     * Sets the value of the mthsAtCurrentRes property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMthsAtCurrentRes(BigInteger value) {
        this.mthsAtCurrentRes = value;
    }

    /**
     * Gets the value of the applicantEducLvl property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getApplicantEducLvl() {
        return applicantEducLvl;
    }

    /**
     * Sets the value of the applicantEducLvl property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setApplicantEducLvl(BigInteger value) {
        this.applicantEducLvl = value;
    }

    /**
     * Gets the value of the housingType property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getHousingType() {
        return housingType;
    }

    /**
     * Sets the value of the housingType property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setHousingType(BigInteger value) {
        this.housingType = value;
    }

    /**
     * Gets the value of the existingAcctFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExistingAcctFlag() {
        return existingAcctFlag;
    }

    /**
     * Sets the value of the existingAcctFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExistingAcctFlag(String value) {
        this.existingAcctFlag = value;
    }

    /**
     * Gets the value of the multipleAppFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMultipleAppFlag() {
        return multipleAppFlag;
    }

    /**
     * Sets the value of the multipleAppFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMultipleAppFlag(String value) {
        this.multipleAppFlag = value;
    }

    /**
     * Gets the value of the addrDiscrepancyFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddrDiscrepancyFlag() {
        return addrDiscrepancyFlag;
    }

    /**
     * Sets the value of the addrDiscrepancyFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddrDiscrepancyFlag(String value) {
        this.addrDiscrepancyFlag = value;
    }

    /**
     * Gets the value of the redFlagAlert property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRedFlagAlert() {
        return redFlagAlert;
    }

    /**
     * Sets the value of the redFlagAlert property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRedFlagAlert(String value) {
        this.redFlagAlert = value;
    }

    /**
     * Gets the value of the identityAlert property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentityAlert() {
        return identityAlert;
    }

    /**
     * Sets the value of the identityAlert property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentityAlert(String value) {
        this.identityAlert = value;
    }

    /**
     * Gets the value of the activeMilitaryAlert property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActiveMilitaryAlert() {
        return activeMilitaryAlert;
    }

    /**
     * Sets the value of the activeMilitaryAlert property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActiveMilitaryAlert(String value) {
        this.activeMilitaryAlert = value;
    }

    /**
     * Gets the value of the appSSNInvalid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAppSSNInvalid() {
        return appSSNInvalid;
    }

    /**
     * Sets the value of the appSSNInvalid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAppSSNInvalid(String value) {
        this.appSSNInvalid = value;
    }

    /**
     * Gets the value of the consumerStatement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConsumerStatement() {
        return consumerStatement;
    }

    /**
     * Sets the value of the consumerStatement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConsumerStatement(String value) {
        this.consumerStatement = value;
    }

    /**
     * Gets the value of the ofacAlert property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOFACAlert() {
        return ofacAlert;
    }

    /**
     * Sets the value of the ofacAlert property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOFACAlert(String value) {
        this.ofacAlert = value;
    }

    /**
     * Gets the value of the retiredFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRetiredFlag() {
        return retiredFlag;
    }

    /**
     * Sets the value of the retiredFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRetiredFlag(String value) {
        this.retiredFlag = value;
    }

    /**
     * Gets the value of the employedFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmployedFlag() {
        return employedFlag;
    }

    /**
     * Sets the value of the employedFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmployedFlag(String value) {
        this.employedFlag = value;
    }

    /**
     * Gets the value of the nbrOfOpenTaxLiens property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNbrOfOpenTaxLiens() {
        return nbrOfOpenTaxLiens;
    }

    /**
     * Sets the value of the nbrOfOpenTaxLiens property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNbrOfOpenTaxLiens(BigInteger value) {
        this.nbrOfOpenTaxLiens = value;
    }

    /**
     * Gets the value of the decisionCBName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDecisionCBName() {
        return decisionCBName;
    }

    /**
     * Sets the value of the decisionCBName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDecisionCBName(String value) {
        this.decisionCBName = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setState(String value) {
        this.state = value;
    }

    /**
     * Gets the value of the applicantBureauInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ApplicantBureauInfo }
     *     
     */
    public ApplicantBureauInfo getApplicantBureauInfo() {
        return applicantBureauInfo;
    }

    /**
     * Sets the value of the applicantBureauInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApplicantBureauInfo }
     *     
     */
    public void setApplicantBureauInfo(ApplicantBureauInfo value) {
        this.applicantBureauInfo = value;
    }

    /**
     * Gets the value of the prevAppDebtOfApplicant property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPrevAppDebtOfApplicant() {
        return prevAppDebtOfApplicant;
    }

    /**
     * Sets the value of the prevAppDebtOfApplicant property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPrevAppDebtOfApplicant(BigDecimal value) {
        this.prevAppDebtOfApplicant = value;
    }

    /**
     * Gets the value of the debtOfApplicant property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDebtOfApplicant() {
        return debtOfApplicant;
    }

    /**
     * Sets the value of the debtOfApplicant property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDebtOfApplicant(BigDecimal value) {
        this.debtOfApplicant = value;
    }

    /**
     * Gets the value of the prevAppMonthlyIncome property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPrevAppMonthlyIncome() {
        return prevAppMonthlyIncome;
    }

    /**
     * Sets the value of the prevAppMonthlyIncome property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPrevAppMonthlyIncome(BigDecimal value) {
        this.prevAppMonthlyIncome = value;
    }

    /**
     * Gets the value of the appMonthlyIncome property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAppMonthlyIncome() {
        return appMonthlyIncome;
    }

    /**
     * Sets the value of the appMonthlyIncome property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAppMonthlyIncome(BigDecimal value) {
        this.appMonthlyIncome = value;
    }

    /**
     * Gets the value of the nameDiscrepancyFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameDiscrepancyFlag() {
        return nameDiscrepancyFlag;
    }

    /**
     * Sets the value of the nameDiscrepancyFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameDiscrepancyFlag(String value) {
        this.nameDiscrepancyFlag = value;
    }

    /**
     * Gets the value of the phoneNumberDiscrepancyFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhoneNumberDiscrepancyFlag() {
        return phoneNumberDiscrepancyFlag;
    }

    /**
     * Sets the value of the phoneNumberDiscrepancyFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhoneNumberDiscrepancyFlag(String value) {
        this.phoneNumberDiscrepancyFlag = value;
    }

    /**
     * Gets the value of the ssnDiscrepancyFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSSNDiscrepancyFlag() {
        return ssnDiscrepancyFlag;
    }

    /**
     * Sets the value of the ssnDiscrepancyFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSSNDiscrepancyFlag(String value) {
        this.ssnDiscrepancyFlag = value;
    }

    /**
     * Gets the value of the cvIscore property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCVIscore() {
        return cvIscore;
    }

    /**
     * Sets the value of the cvIscore property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCVIscore(BigInteger value) {
        this.cvIscore = value;
    }

}
