//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.19 at 04:10:08 PM IST 
//


package com.migration.soapservice.entity;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Application Info
 * 
 * <p>Java class for ApplicationInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ApplicationInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DSSO" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ProductType" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="AppRcvdDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="ReScoreFlag" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Program" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="RandomNumber1" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;totalDigits value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="RandomNumber2" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;totalDigits value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="RandomNumber3" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;totalDigits value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Dealership">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="FICODecisioningScore">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;totalDigits value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="VantageDecisioningScore" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;totalDigits value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Tier" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="DeliveryChannel">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="BusinessType" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="BrokerFlag" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="AppType" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="FinancialInfo" type="{http://migration.com/soapservice/entity}FinancialInfo"/>
 *         &lt;element name="CollateralInfo" type="{http://migration.com/soapservice/entity}CollateralInfo"/>
 *         &lt;element name="DealerNumber" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PrevApplicationReceivedDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="PrevContractApplicationFundingStatus" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PrevCreditApplicationDecisionStatus" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="CountofMultipleApplications" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;totalDigits value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PrevMutiAppRiskScoreScorecardName" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="40"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PrevRiskScoreScorecardName" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="40"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PrevAppNbr" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;totalDigits value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PrevFinalDecisionDecCategory" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PrevDealerNumber" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PrevProductType" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ApplicationInfo", propOrder = {
    "dsso",
    "productType",
    "appRcvdDate",
    "reScoreFlag",
    "program",
    "randomNumber1",
    "randomNumber2",
    "randomNumber3",
    "dealership",
    "ficoDecisioningScore",
    "vantageDecisioningScore",
    "tier",
    "deliveryChannel",
    "businessType",
    "brokerFlag",
    "appType",
    "financialInfo",
    "collateralInfo",
    "dealerNumber",
    "prevApplicationReceivedDate",
    "prevContractApplicationFundingStatus",
    "prevCreditApplicationDecisionStatus",
    "countofMultipleApplications",
    "prevMutiAppRiskScoreScorecardName",
    "prevRiskScoreScorecardName",
    "prevAppNbr",
    "prevFinalDecisionDecCategory",
    "prevDealerNumber",
    "prevProductType"
})
public class ApplicationInfo {

    @XmlElement(name = "DSSO")
    protected String dsso;
    @XmlElement(name = "ProductType")
    protected String productType;
    @XmlElement(name = "AppRcvdDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar appRcvdDate;
    @XmlElement(name = "ReScoreFlag")
    protected String reScoreFlag;
    @XmlElement(name = "Program")
    protected String program;
    @XmlElement(name = "RandomNumber1")
    protected BigInteger randomNumber1;
    @XmlElement(name = "RandomNumber2")
    protected BigInteger randomNumber2;
    @XmlElement(name = "RandomNumber3")
    protected BigInteger randomNumber3;
    @XmlElement(name = "Dealership", required = true)
    protected String dealership;
    @XmlElement(name = "FICODecisioningScore", required = true)
    protected BigInteger ficoDecisioningScore;
    @XmlElement(name = "VantageDecisioningScore")
    protected BigInteger vantageDecisioningScore;
    @XmlElement(name = "Tier")
    protected String tier;
    @XmlElement(name = "DeliveryChannel", required = true)
    protected String deliveryChannel;
    @XmlElement(name = "BusinessType")
    protected String businessType;
    @XmlElement(name = "BrokerFlag")
    protected String brokerFlag;
    @XmlElement(name = "AppType")
    protected String appType;
    @XmlElement(name = "FinancialInfo", required = true)
    protected FinancialInfo financialInfo;
    @XmlElement(name = "CollateralInfo", required = true)
    protected CollateralInfo collateralInfo;
    @XmlElement(name = "DealerNumber")
    protected String dealerNumber;
    @XmlElement(name = "PrevApplicationReceivedDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar prevApplicationReceivedDate;
    @XmlElement(name = "PrevContractApplicationFundingStatus")
    protected String prevContractApplicationFundingStatus;
    @XmlElement(name = "PrevCreditApplicationDecisionStatus")
    protected String prevCreditApplicationDecisionStatus;
    @XmlElement(name = "CountofMultipleApplications")
    protected BigInteger countofMultipleApplications;
    @XmlElement(name = "PrevMutiAppRiskScoreScorecardName")
    protected String prevMutiAppRiskScoreScorecardName;
    @XmlElement(name = "PrevRiskScoreScorecardName")
    protected String prevRiskScoreScorecardName;
    @XmlElement(name = "PrevAppNbr")
    protected BigInteger prevAppNbr;
    @XmlElement(name = "PrevFinalDecisionDecCategory")
    protected String prevFinalDecisionDecCategory;
    @XmlElement(name = "PrevDealerNumber")
    protected String prevDealerNumber;
    @XmlElement(name = "PrevProductType")
    protected String prevProductType;

    /**
     * Gets the value of the dsso property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDSSO() {
        return dsso;
    }

    /**
     * Sets the value of the dsso property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDSSO(String value) {
        this.dsso = value;
    }

    /**
     * Gets the value of the productType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductType() {
        return productType;
    }

    /**
     * Sets the value of the productType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductType(String value) {
        this.productType = value;
    }

    /**
     * Gets the value of the appRcvdDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAppRcvdDate() {
        return appRcvdDate;
    }

    /**
     * Sets the value of the appRcvdDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAppRcvdDate(XMLGregorianCalendar value) {
        this.appRcvdDate = value;
    }

    /**
     * Gets the value of the reScoreFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReScoreFlag() {
        return reScoreFlag;
    }

    /**
     * Sets the value of the reScoreFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReScoreFlag(String value) {
        this.reScoreFlag = value;
    }

    /**
     * Gets the value of the program property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProgram() {
        return program;
    }

    /**
     * Sets the value of the program property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProgram(String value) {
        this.program = value;
    }

    /**
     * Gets the value of the randomNumber1 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRandomNumber1() {
        return randomNumber1;
    }

    /**
     * Sets the value of the randomNumber1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRandomNumber1(BigInteger value) {
        this.randomNumber1 = value;
    }

    /**
     * Gets the value of the randomNumber2 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRandomNumber2() {
        return randomNumber2;
    }

    /**
     * Sets the value of the randomNumber2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRandomNumber2(BigInteger value) {
        this.randomNumber2 = value;
    }

    /**
     * Gets the value of the randomNumber3 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRandomNumber3() {
        return randomNumber3;
    }

    /**
     * Sets the value of the randomNumber3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRandomNumber3(BigInteger value) {
        this.randomNumber3 = value;
    }

    /**
     * Gets the value of the dealership property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDealership() {
        return dealership;
    }

    /**
     * Sets the value of the dealership property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDealership(String value) {
        this.dealership = value;
    }

    /**
     * Gets the value of the ficoDecisioningScore property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFICODecisioningScore() {
        return ficoDecisioningScore;
    }

    /**
     * Sets the value of the ficoDecisioningScore property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFICODecisioningScore(BigInteger value) {
        this.ficoDecisioningScore = value;
    }

    /**
     * Gets the value of the vantageDecisioningScore property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getVantageDecisioningScore() {
        return vantageDecisioningScore;
    }

    /**
     * Sets the value of the vantageDecisioningScore property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setVantageDecisioningScore(BigInteger value) {
        this.vantageDecisioningScore = value;
    }

    /**
     * Gets the value of the tier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTier() {
        return tier;
    }

    /**
     * Sets the value of the tier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTier(String value) {
        this.tier = value;
    }

    /**
     * Gets the value of the deliveryChannel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeliveryChannel() {
        return deliveryChannel;
    }

    /**
     * Sets the value of the deliveryChannel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeliveryChannel(String value) {
        this.deliveryChannel = value;
    }

    /**
     * Gets the value of the businessType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBusinessType() {
        return businessType;
    }

    /**
     * Sets the value of the businessType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBusinessType(String value) {
        this.businessType = value;
    }

    /**
     * Gets the value of the brokerFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrokerFlag() {
        return brokerFlag;
    }

    /**
     * Sets the value of the brokerFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrokerFlag(String value) {
        this.brokerFlag = value;
    }

    /**
     * Gets the value of the appType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAppType() {
        return appType;
    }

    /**
     * Sets the value of the appType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAppType(String value) {
        this.appType = value;
    }

    /**
     * Gets the value of the financialInfo property.
     * 
     * @return
     *     possible object is
     *     {@link FinancialInfo }
     *     
     */
    public FinancialInfo getFinancialInfo() {
        return financialInfo;
    }

    /**
     * Sets the value of the financialInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link FinancialInfo }
     *     
     */
    public void setFinancialInfo(FinancialInfo value) {
        this.financialInfo = value;
    }

    /**
     * Gets the value of the collateralInfo property.
     * 
     * @return
     *     possible object is
     *     {@link CollateralInfo }
     *     
     */
    public CollateralInfo getCollateralInfo() {
        return collateralInfo;
    }

    /**
     * Sets the value of the collateralInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link CollateralInfo }
     *     
     */
    public void setCollateralInfo(CollateralInfo value) {
        this.collateralInfo = value;
    }

    /**
     * Gets the value of the dealerNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDealerNumber() {
        return dealerNumber;
    }

    /**
     * Sets the value of the dealerNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDealerNumber(String value) {
        this.dealerNumber = value;
    }

    /**
     * Gets the value of the prevApplicationReceivedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPrevApplicationReceivedDate() {
        return prevApplicationReceivedDate;
    }

    /**
     * Sets the value of the prevApplicationReceivedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPrevApplicationReceivedDate(XMLGregorianCalendar value) {
        this.prevApplicationReceivedDate = value;
    }

    /**
     * Gets the value of the prevContractApplicationFundingStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrevContractApplicationFundingStatus() {
        return prevContractApplicationFundingStatus;
    }

    /**
     * Sets the value of the prevContractApplicationFundingStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrevContractApplicationFundingStatus(String value) {
        this.prevContractApplicationFundingStatus = value;
    }

    /**
     * Gets the value of the prevCreditApplicationDecisionStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrevCreditApplicationDecisionStatus() {
        return prevCreditApplicationDecisionStatus;
    }

    /**
     * Sets the value of the prevCreditApplicationDecisionStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrevCreditApplicationDecisionStatus(String value) {
        this.prevCreditApplicationDecisionStatus = value;
    }

    /**
     * Gets the value of the countofMultipleApplications property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCountofMultipleApplications() {
        return countofMultipleApplications;
    }

    /**
     * Sets the value of the countofMultipleApplications property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCountofMultipleApplications(BigInteger value) {
        this.countofMultipleApplications = value;
    }

    /**
     * Gets the value of the prevMutiAppRiskScoreScorecardName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrevMutiAppRiskScoreScorecardName() {
        return prevMutiAppRiskScoreScorecardName;
    }

    /**
     * Sets the value of the prevMutiAppRiskScoreScorecardName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrevMutiAppRiskScoreScorecardName(String value) {
        this.prevMutiAppRiskScoreScorecardName = value;
    }

    /**
     * Gets the value of the prevRiskScoreScorecardName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrevRiskScoreScorecardName() {
        return prevRiskScoreScorecardName;
    }

    /**
     * Sets the value of the prevRiskScoreScorecardName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrevRiskScoreScorecardName(String value) {
        this.prevRiskScoreScorecardName = value;
    }

    /**
     * Gets the value of the prevAppNbr property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPrevAppNbr() {
        return prevAppNbr;
    }

    /**
     * Sets the value of the prevAppNbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPrevAppNbr(BigInteger value) {
        this.prevAppNbr = value;
    }

    /**
     * Gets the value of the prevFinalDecisionDecCategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrevFinalDecisionDecCategory() {
        return prevFinalDecisionDecCategory;
    }

    /**
     * Sets the value of the prevFinalDecisionDecCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrevFinalDecisionDecCategory(String value) {
        this.prevFinalDecisionDecCategory = value;
    }

    /**
     * Gets the value of the prevDealerNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrevDealerNumber() {
        return prevDealerNumber;
    }

    /**
     * Sets the value of the prevDealerNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrevDealerNumber(String value) {
        this.prevDealerNumber = value;
    }

    /**
     * Gets the value of the prevProductType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrevProductType() {
        return prevProductType;
    }

    /**
     * Sets the value of the prevProductType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrevProductType(String value) {
        this.prevProductType = value;
    }

}
