//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.19 at 04:10:08 PM IST 
//


package com.migration.soapservice.entity;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ApplicantBureauData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ApplicantBureauData">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AppFICOScore">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;totalDigits value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="AppVantageScore">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;totalDigits value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="BureauHitNoHitFlag" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ARFFiles" type="{http://migration.com/soapservice/entity}ARFFiles" maxOccurs="5" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ApplicantBureauData", propOrder = {
    "appFICOScore",
    "appVantageScore",
    "bureauHitNoHitFlag",
    "arfFiles"
})
public class ApplicantBureauData {

    @XmlElement(name = "AppFICOScore", required = true)
    protected BigInteger appFICOScore;
    @XmlElement(name = "AppVantageScore", required = true)
    protected BigInteger appVantageScore;
    @XmlElement(name = "BureauHitNoHitFlag")
    protected String bureauHitNoHitFlag;
    @XmlElement(name = "ARFFiles")
    protected List<ARFFiles> arfFiles;

    /**
     * Gets the value of the appFICOScore property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAppFICOScore() {
        return appFICOScore;
    }

    /**
     * Sets the value of the appFICOScore property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAppFICOScore(BigInteger value) {
        this.appFICOScore = value;
    }

    /**
     * Gets the value of the appVantageScore property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAppVantageScore() {
        return appVantageScore;
    }

    /**
     * Sets the value of the appVantageScore property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAppVantageScore(BigInteger value) {
        this.appVantageScore = value;
    }

    /**
     * Gets the value of the bureauHitNoHitFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBureauHitNoHitFlag() {
        return bureauHitNoHitFlag;
    }

    /**
     * Sets the value of the bureauHitNoHitFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBureauHitNoHitFlag(String value) {
        this.bureauHitNoHitFlag = value;
    }

    /**
     * Gets the value of the arfFiles property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the arfFiles property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getARFFiles().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ARFFiles }
     * 
     * 
     */
    public List<ARFFiles> getARFFiles() {
        if (arfFiles == null) {
            arfFiles = new ArrayList<ARFFiles>();
        }
        return this.arfFiles;
    }

}
