//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.19 at 04:10:08 PM IST 
//


package com.migration.soapservice.entity;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * CoApplicantInfo information
 * 
 * <p>Java class for CoApplicantInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CoApplicantInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AppType" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ApplicantInfo" type="{http://migration.com/soapservice/entity}ApplicantInfo" minOccurs="0"/>
 *         &lt;element name="PrevCoAppType" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CoApplicantInfo", propOrder = {
    "appType",
    "applicantInfo",
    "prevCoAppType"
})
public class CoApplicantInfo {

    @XmlElement(name = "AppType")
    protected String appType;
    @XmlElement(name = "ApplicantInfo")
    protected ApplicantInfo applicantInfo;
    @XmlElement(name = "PrevCoAppType")
    protected String prevCoAppType;

    /**
     * Gets the value of the appType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAppType() {
        return appType;
    }

    /**
     * Sets the value of the appType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAppType(String value) {
        this.appType = value;
    }

    /**
     * Gets the value of the applicantInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ApplicantInfo }
     *     
     */
    public ApplicantInfo getApplicantInfo() {
        return applicantInfo;
    }

    /**
     * Sets the value of the applicantInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApplicantInfo }
     *     
     */
    public void setApplicantInfo(ApplicantInfo value) {
        this.applicantInfo = value;
    }

    /**
     * Gets the value of the prevCoAppType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrevCoAppType() {
        return prevCoAppType;
    }

    /**
     * Sets the value of the prevCoAppType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrevCoAppType(String value) {
        this.prevCoAppType = value;
    }

}
