//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.19 at 04:10:08 PM IST 
//


package com.migration.soapservice.entity;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DataOutcome complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DataOutcome">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="StandardOutcomes" type="{http://migration.com/soapservice/entity}StrategyOutcome" minOccurs="0"/>
 *         &lt;element name="Grade" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DataOutcome", propOrder = {
    "standardOutcomes",
    "grade"
})
public class DataOutcome {

    @XmlElement(name = "StandardOutcomes")
    protected StrategyOutcome standardOutcomes;
    @XmlElement(name = "Grade")
    protected String grade;

    /**
     * Gets the value of the standardOutcomes property.
     * 
     * @return
     *     possible object is
     *     {@link StrategyOutcome }
     *     
     */
    public StrategyOutcome getStandardOutcomes() {
        return standardOutcomes;
    }

    /**
     * Sets the value of the standardOutcomes property.
     * 
     * @param value
     *     allowed object is
     *     {@link StrategyOutcome }
     *     
     */
    public void setStandardOutcomes(StrategyOutcome value) {
        this.standardOutcomes = value;
    }

    /**
     * Gets the value of the grade property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGrade() {
        return grade;
    }

    /**
     * Sets the value of the grade property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGrade(String value) {
        this.grade = value;
    }

}
