//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.19 at 04:10:08 PM IST 
//


package com.migration.soapservice.entity;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DecisionCategoriesOutcome complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DecisionCategoriesOutcome">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ScriptNodeID" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;totalDigits value="7"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="StandardOutcomes" type="{http://migration.com/soapservice/entity}StrategyOutcome" minOccurs="0"/>
 *         &lt;element name="DecisionCategoryOutcome" type="{http://migration.com/soapservice/entity}DecisionCategoryOutcome" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DecisionCategoriesOutcome", propOrder = {
    "scriptNodeID",
    "standardOutcomes",
    "decisionCategoryOutcome"
})
public class DecisionCategoriesOutcome {

    @XmlElement(name = "ScriptNodeID")
    protected BigInteger scriptNodeID;
    @XmlElement(name = "StandardOutcomes")
    protected StrategyOutcome standardOutcomes;
    @XmlElement(name = "DecisionCategoryOutcome")
    protected DecisionCategoryOutcome decisionCategoryOutcome;

    /**
     * Gets the value of the scriptNodeID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getScriptNodeID() {
        return scriptNodeID;
    }

    /**
     * Sets the value of the scriptNodeID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setScriptNodeID(BigInteger value) {
        this.scriptNodeID = value;
    }

    /**
     * Gets the value of the standardOutcomes property.
     * 
     * @return
     *     possible object is
     *     {@link StrategyOutcome }
     *     
     */
    public StrategyOutcome getStandardOutcomes() {
        return standardOutcomes;
    }

    /**
     * Sets the value of the standardOutcomes property.
     * 
     * @param value
     *     allowed object is
     *     {@link StrategyOutcome }
     *     
     */
    public void setStandardOutcomes(StrategyOutcome value) {
        this.standardOutcomes = value;
    }

    /**
     * Gets the value of the decisionCategoryOutcome property.
     * 
     * @return
     *     possible object is
     *     {@link DecisionCategoryOutcome }
     *     
     */
    public DecisionCategoryOutcome getDecisionCategoryOutcome() {
        return decisionCategoryOutcome;
    }

    /**
     * Sets the value of the decisionCategoryOutcome property.
     * 
     * @param value
     *     allowed object is
     *     {@link DecisionCategoryOutcome }
     *     
     */
    public void setDecisionCategoryOutcome(DecisionCategoryOutcome value) {
        this.decisionCategoryOutcome = value;
    }

}
