//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.19 at 04:10:08 PM IST 
//


package com.migration.soapservice.entity;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DecisionOutcome complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DecisionOutcome">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ScriptNodeID" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;totalDigits value="7"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="RsnCode1" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="RsnCode2" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="RsnCode3" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="RsnCode4" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DecisionOutcome", propOrder = {
    "scriptNodeID",
    "rsnCode1",
    "rsnCode2",
    "rsnCode3",
    "rsnCode4"
})
public class DecisionOutcome {

    @XmlElement(name = "ScriptNodeID")
    protected BigInteger scriptNodeID;
    @XmlElement(name = "RsnCode1")
    protected String rsnCode1;
    @XmlElement(name = "RsnCode2")
    protected String rsnCode2;
    @XmlElement(name = "RsnCode3")
    protected String rsnCode3;
    @XmlElement(name = "RsnCode4")
    protected String rsnCode4;

    /**
     * Gets the value of the scriptNodeID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getScriptNodeID() {
        return scriptNodeID;
    }

    /**
     * Sets the value of the scriptNodeID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setScriptNodeID(BigInteger value) {
        this.scriptNodeID = value;
    }

    /**
     * Gets the value of the rsnCode1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRsnCode1() {
        return rsnCode1;
    }

    /**
     * Sets the value of the rsnCode1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRsnCode1(String value) {
        this.rsnCode1 = value;
    }

    /**
     * Gets the value of the rsnCode2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRsnCode2() {
        return rsnCode2;
    }

    /**
     * Sets the value of the rsnCode2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRsnCode2(String value) {
        this.rsnCode2 = value;
    }

    /**
     * Gets the value of the rsnCode3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRsnCode3() {
        return rsnCode3;
    }

    /**
     * Sets the value of the rsnCode3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRsnCode3(String value) {
        this.rsnCode3 = value;
    }

    /**
     * Gets the value of the rsnCode4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRsnCode4() {
        return rsnCode4;
    }

    /**
     * Sets the value of the rsnCode4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRsnCode4(String value) {
        this.rsnCode4 = value;
    }

}
