//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.19 at 03:47:26 PM IST 
//


package com.migration.soapservice.entity;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DecisionEngineEvalRe complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DecisionEngineEvalRe">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DecisionEngineEval" type="{http://migration.com/soapservice/entity}DecisionEngineEval"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DecisionEngineEvalRe", propOrder = {
    "decisionEngineEval"
})
public class DecisionEngineEvalRe {

    @XmlElement(name = "DecisionEngineEval", required = true)
    protected DecisionEngineEval decisionEngineEval;

    /**
     * Gets the value of the decisionEngineEval property.
     * 
     * @return
     *     possible object is
     *     {@link DecisionEngineEval }
     *     
     */
    public DecisionEngineEval getDecisionEngineEval() {
        return decisionEngineEval;
    }

    /**
     * Sets the value of the decisionEngineEval property.
     * 
     * @param value
     *     allowed object is
     *     {@link DecisionEngineEval }
     *     
     */
    public void setDecisionEngineEval(DecisionEngineEval value) {
        this.decisionEngineEval = value;
    }

}
