//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.19 at 04:10:08 PM IST 
//


package com.migration.soapservice.entity;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Root request element, includes the details of
 * 				PrevAppDebtOfCoApplicant, Applicant, Co-Applicant details
 * 			
 * 
 * <p>Java class for DecisionEngineEval complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DecisionEngineEval">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AppNbr" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;totalDigits value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="AliasName" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="8"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Signature" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="8"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ApplicationInfo" type="{http://migration.com/soapservice/entity}ApplicationInfo"/>
 *         &lt;element name="ApplicantInfo" type="{http://migration.com/soapservice/entity}ApplicantInfo" maxOccurs="2"/>
 *         &lt;element name="CoApplicantInfo" type="{http://migration.com/soapservice/entity}CoApplicantInfo" maxOccurs="2" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DecisionEngineEval", propOrder = {
    "appNbr",
    "aliasName",
    "signature",
    "applicationInfo",
    "applicantInfo",
    "coApplicantInfo"
})
@XmlRootElement(name = "DecisionEngineEval")
public class DecisionEngineEval {

    @XmlElement(name = "AppNbr")
    protected BigInteger appNbr;
    @XmlElement(name = "AliasName")
    protected String aliasName;
    @XmlElement(name = "Signature")
    protected String signature;
    @XmlElement(name = "ApplicationInfo", required = true)
    protected ApplicationInfo applicationInfo;
    @XmlElement(name = "ApplicantInfo", required = true)
    protected List<ApplicantInfo> applicantInfo;
    @XmlElement(name = "CoApplicantInfo")
    protected List<CoApplicantInfo> coApplicantInfo;

    /**
     * Gets the value of the appNbr property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAppNbr() {
        return appNbr;
    }

    /**
     * Sets the value of the appNbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAppNbr(BigInteger value) {
        this.appNbr = value;
    }

    /**
     * Gets the value of the aliasName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAliasName() {
        return aliasName;
    }

    /**
     * Sets the value of the aliasName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAliasName(String value) {
        this.aliasName = value;
    }

    /**
     * Gets the value of the signature property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSignature() {
        return signature;
    }

    /**
     * Sets the value of the signature property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSignature(String value) {
        this.signature = value;
    }

    /**
     * Gets the value of the applicationInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ApplicationInfo }
     *     
     */
    public ApplicationInfo getApplicationInfo() {
        return applicationInfo;
    }

    /**
     * Sets the value of the applicationInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApplicationInfo }
     *     
     */
    public void setApplicationInfo(ApplicationInfo value) {
        this.applicationInfo = value;
    }

    /**
     * Gets the value of the applicantInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the applicantInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getApplicantInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ApplicantInfo }
     * 
     * 
     */
    public List<ApplicantInfo> getApplicantInfo() {
        if (applicantInfo == null) {
            applicantInfo = new ArrayList<ApplicantInfo>();
        }
        return this.applicantInfo;
    }

    /**
     * Gets the value of the coApplicantInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the coApplicantInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCoApplicantInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CoApplicantInfo }
     * 
     * 
     */
    public List<CoApplicantInfo> getCoApplicantInfo() {
        if (coApplicantInfo == null) {
            coApplicantInfo = new ArrayList<CoApplicantInfo>();
        }
        return this.coApplicantInfo;
    }

	@Override
	public String toString() {
		return "DecisionEngineEval [appNbr=" + appNbr + ", aliasName=" + aliasName + ", signature=" + signature
				+ ", applicationInfo=" + applicationInfo + ", applicantInfo=" + applicantInfo + ", coApplicantInfo="
				+ coApplicantInfo + "]";
	}

}
