//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.19 at 04:10:08 PM IST 
//


package com.migration.soapservice.entity;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Financial Info
 * 
 * <p>Java class for FinancialInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FinancialInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AmountFinanced">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="8"/>
 *               &lt;fractionDigits value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="CashPrice" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="8"/>
 *               &lt;fractionDigits value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="EstDealerCost" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="8"/>
 *               &lt;fractionDigits value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="CapCost" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="8"/>
 *               &lt;fractionDigits value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="MSRP" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="8"/>
 *               &lt;fractionDigits value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="NetCapCost" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="8"/>
 *               &lt;fractionDigits value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PIR">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="5"/>
 *               &lt;fractionDigits value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="DIR">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="5"/>
 *               &lt;fractionDigits value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PctAdvanced">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="5"/>
 *               &lt;fractionDigits value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="AppTerm" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;totalDigits value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PrevPctAdvanced" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="5"/>
 *               &lt;fractionDigits value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PrevMSRP" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="8"/>
 *               &lt;fractionDigits value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PrevEstDealerCost" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="8"/>
 *               &lt;fractionDigits value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PrevPIR" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="5"/>
 *               &lt;fractionDigits value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PrevAppTerm" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;totalDigits value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PrevPaymentProbability" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;totalDigits value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PrevAmountFinanced" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="8"/>
 *               &lt;fractionDigits value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PrevAppTotalIncome" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="8"/>
 *               &lt;fractionDigits value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="AppTotalIncome" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="8"/>
 *               &lt;fractionDigits value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PrevAppDIR" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="5"/>
 *               &lt;fractionDigits value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="CombinedDIR" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="5"/>
 *               &lt;fractionDigits value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PrevAppMonthlyPayment" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="8"/>
 *               &lt;fractionDigits value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="MonthlyPayment" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="8"/>
 *               &lt;fractionDigits value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FinancialInfo", propOrder = {
    "amountFinanced",
    "cashPrice",
    "estDealerCost",
    "capCost",
    "msrp",
    "netCapCost",
    "pir",
    "dir",
    "pctAdvanced",
    "appTerm",
    "prevPctAdvanced",
    "prevMSRP",
    "prevEstDealerCost",
    "prevPIR",
    "prevAppTerm",
    "prevPaymentProbability",
    "prevAmountFinanced",
    "prevAppTotalIncome",
    "appTotalIncome",
    "prevAppDIR",
    "combinedDIR",
    "prevAppMonthlyPayment",
    "monthlyPayment"
})
public class FinancialInfo {

    @XmlElement(name = "AmountFinanced", required = true)
    protected BigDecimal amountFinanced;
    @XmlElement(name = "CashPrice")
    protected BigDecimal cashPrice;
    @XmlElement(name = "EstDealerCost")
    protected BigDecimal estDealerCost;
    @XmlElement(name = "CapCost")
    protected BigDecimal capCost;
    @XmlElement(name = "MSRP")
    protected BigDecimal msrp;
    @XmlElement(name = "NetCapCost")
    protected BigDecimal netCapCost;
    @XmlElement(name = "PIR", required = true)
    protected BigDecimal pir;
    @XmlElement(name = "DIR", required = true)
    protected BigDecimal dir;
    @XmlElement(name = "PctAdvanced", required = true)
    protected BigDecimal pctAdvanced;
    @XmlElement(name = "AppTerm")
    protected BigInteger appTerm;
    @XmlElement(name = "PrevPctAdvanced")
    protected BigDecimal prevPctAdvanced;
    @XmlElement(name = "PrevMSRP")
    protected BigDecimal prevMSRP;
    @XmlElement(name = "PrevEstDealerCost")
    protected BigDecimal prevEstDealerCost;
    @XmlElement(name = "PrevPIR")
    protected BigDecimal prevPIR;
    @XmlElement(name = "PrevAppTerm")
    protected BigInteger prevAppTerm;
    @XmlElement(name = "PrevPaymentProbability")
    protected BigInteger prevPaymentProbability;
    @XmlElement(name = "PrevAmountFinanced")
    protected BigDecimal prevAmountFinanced;
    @XmlElement(name = "PrevAppTotalIncome")
    protected BigDecimal prevAppTotalIncome;
    @XmlElement(name = "AppTotalIncome")
    protected BigDecimal appTotalIncome;
    @XmlElement(name = "PrevAppDIR")
    protected BigDecimal prevAppDIR;
    @XmlElement(name = "CombinedDIR")
    protected BigDecimal combinedDIR;
    @XmlElement(name = "PrevAppMonthlyPayment")
    protected BigDecimal prevAppMonthlyPayment;
    @XmlElement(name = "MonthlyPayment")
    protected BigDecimal monthlyPayment;

    /**
     * Gets the value of the amountFinanced property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAmountFinanced() {
        return amountFinanced;
    }

    /**
     * Sets the value of the amountFinanced property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAmountFinanced(BigDecimal value) {
        this.amountFinanced = value;
    }

    /**
     * Gets the value of the cashPrice property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCashPrice() {
        return cashPrice;
    }

    /**
     * Sets the value of the cashPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCashPrice(BigDecimal value) {
        this.cashPrice = value;
    }

    /**
     * Gets the value of the estDealerCost property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getEstDealerCost() {
        return estDealerCost;
    }

    /**
     * Sets the value of the estDealerCost property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setEstDealerCost(BigDecimal value) {
        this.estDealerCost = value;
    }

    /**
     * Gets the value of the capCost property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCapCost() {
        return capCost;
    }

    /**
     * Sets the value of the capCost property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCapCost(BigDecimal value) {
        this.capCost = value;
    }

    /**
     * Gets the value of the msrp property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMSRP() {
        return msrp;
    }

    /**
     * Sets the value of the msrp property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMSRP(BigDecimal value) {
        this.msrp = value;
    }

    /**
     * Gets the value of the netCapCost property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNetCapCost() {
        return netCapCost;
    }

    /**
     * Sets the value of the netCapCost property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNetCapCost(BigDecimal value) {
        this.netCapCost = value;
    }

    /**
     * Gets the value of the pir property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPIR() {
        return pir;
    }

    /**
     * Sets the value of the pir property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPIR(BigDecimal value) {
        this.pir = value;
    }

    /**
     * Gets the value of the dir property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDIR() {
        return dir;
    }

    /**
     * Sets the value of the dir property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDIR(BigDecimal value) {
        this.dir = value;
    }

    /**
     * Gets the value of the pctAdvanced property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPctAdvanced() {
        return pctAdvanced;
    }

    /**
     * Sets the value of the pctAdvanced property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPctAdvanced(BigDecimal value) {
        this.pctAdvanced = value;
    }

    /**
     * Gets the value of the appTerm property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAppTerm() {
        return appTerm;
    }

    /**
     * Sets the value of the appTerm property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAppTerm(BigInteger value) {
        this.appTerm = value;
    }

    /**
     * Gets the value of the prevPctAdvanced property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPrevPctAdvanced() {
        return prevPctAdvanced;
    }

    /**
     * Sets the value of the prevPctAdvanced property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPrevPctAdvanced(BigDecimal value) {
        this.prevPctAdvanced = value;
    }

    /**
     * Gets the value of the prevMSRP property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPrevMSRP() {
        return prevMSRP;
    }

    /**
     * Sets the value of the prevMSRP property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPrevMSRP(BigDecimal value) {
        this.prevMSRP = value;
    }

    /**
     * Gets the value of the prevEstDealerCost property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPrevEstDealerCost() {
        return prevEstDealerCost;
    }

    /**
     * Sets the value of the prevEstDealerCost property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPrevEstDealerCost(BigDecimal value) {
        this.prevEstDealerCost = value;
    }

    /**
     * Gets the value of the prevPIR property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPrevPIR() {
        return prevPIR;
    }

    /**
     * Sets the value of the prevPIR property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPrevPIR(BigDecimal value) {
        this.prevPIR = value;
    }

    /**
     * Gets the value of the prevAppTerm property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPrevAppTerm() {
        return prevAppTerm;
    }

    /**
     * Sets the value of the prevAppTerm property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPrevAppTerm(BigInteger value) {
        this.prevAppTerm = value;
    }

    /**
     * Gets the value of the prevPaymentProbability property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPrevPaymentProbability() {
        return prevPaymentProbability;
    }

    /**
     * Sets the value of the prevPaymentProbability property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPrevPaymentProbability(BigInteger value) {
        this.prevPaymentProbability = value;
    }

    /**
     * Gets the value of the prevAmountFinanced property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPrevAmountFinanced() {
        return prevAmountFinanced;
    }

    /**
     * Sets the value of the prevAmountFinanced property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPrevAmountFinanced(BigDecimal value) {
        this.prevAmountFinanced = value;
    }

    /**
     * Gets the value of the prevAppTotalIncome property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPrevAppTotalIncome() {
        return prevAppTotalIncome;
    }

    /**
     * Sets the value of the prevAppTotalIncome property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPrevAppTotalIncome(BigDecimal value) {
        this.prevAppTotalIncome = value;
    }

    /**
     * Gets the value of the appTotalIncome property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAppTotalIncome() {
        return appTotalIncome;
    }

    /**
     * Sets the value of the appTotalIncome property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAppTotalIncome(BigDecimal value) {
        this.appTotalIncome = value;
    }

    /**
     * Gets the value of the prevAppDIR property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPrevAppDIR() {
        return prevAppDIR;
    }

    /**
     * Sets the value of the prevAppDIR property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPrevAppDIR(BigDecimal value) {
        this.prevAppDIR = value;
    }

    /**
     * Gets the value of the combinedDIR property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCombinedDIR() {
        return combinedDIR;
    }

    /**
     * Sets the value of the combinedDIR property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCombinedDIR(BigDecimal value) {
        this.combinedDIR = value;
    }

    /**
     * Gets the value of the prevAppMonthlyPayment property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPrevAppMonthlyPayment() {
        return prevAppMonthlyPayment;
    }

    /**
     * Sets the value of the prevAppMonthlyPayment property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPrevAppMonthlyPayment(BigDecimal value) {
        this.prevAppMonthlyPayment = value;
    }

    /**
     * Gets the value of the monthlyPayment property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMonthlyPayment() {
        return monthlyPayment;
    }

    /**
     * Sets the value of the monthlyPayment property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMonthlyPayment(BigDecimal value) {
        this.monthlyPayment = value;
    }

}
