//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.19 at 04:10:08 PM IST 
//


package com.migration.soapservice.entity;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.migration.soapservice.entity package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _DecisionEngineEvalRequest_QNAME = new QName("http://migration.com/soapservice/entity", "DecisionEngineEvalRequest");
    private final static QName _Fault_QNAME = new QName("http://migration.com/soapservice/entity", "Fault");
    private final static QName _DecisionEngineEvalResponse_QNAME = new QName("http://migration.com/soapservice/entity", "DecisionEngineEvalResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.migration.soapservice.entity
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DecisionEngineEvalResponse }
     * 
     */
    public DecisionEngineEvalResponse createDecisionEngineEvalResponse() {
        return new DecisionEngineEvalResponse();
    }

    /**
     * Create an instance of {@link Fault }
     * 
     */
    public Fault createFault() {
        return new Fault();
    }

    /**
     * Create an instance of {@link DecisionEngineEvalRequest }
     * 
     */
    public DecisionEngineEvalRequest createDecisionEngineEvalRequest() {
        return new DecisionEngineEvalRequest();
    }

    /**
     * Create an instance of {@link DataOutcome }
     * 
     */
    public DataOutcome createDataOutcome() {
        return new DataOutcome();
    }

    /**
     * Create an instance of {@link ScorecardOutcome }
     * 
     */
    public ScorecardOutcome createScorecardOutcome() {
        return new ScorecardOutcome();
    }

    /**
     * Create an instance of {@link DecisionCategoryOutcome }
     * 
     */
    public DecisionCategoryOutcome createDecisionCategoryOutcome() {
        return new DecisionCategoryOutcome();
    }

    /**
     * Create an instance of {@link ApplicationInfo }
     * 
     */
    public ApplicationInfo createApplicationInfo() {
        return new ApplicationInfo();
    }

    /**
     * Create an instance of {@link StrategyTableOutcome }
     * 
     */
    public StrategyTableOutcome createStrategyTableOutcome() {
        return new StrategyTableOutcome();
    }

    /**
     * Create an instance of {@link Result }
     * 
     */
    public Result createResult() {
        return new Result();
    }

    /**
     * Create an instance of {@link MultiAppFinancialInfo }
     * 
     */
    public MultiAppFinancialInfo createMultiAppFinancialInfo() {
        return new MultiAppFinancialInfo();
    }

    /**
     * Create an instance of {@link ResponseApplicantInfo }
     * 
     */
    public ResponseApplicantInfo createResponseApplicantInfo() {
        return new ResponseApplicantInfo();
    }

    /**
     * Create an instance of {@link DecisionCategoriesOutcome }
     * 
     */
    public DecisionCategoriesOutcome createDecisionCategoriesOutcome() {
        return new DecisionCategoriesOutcome();
    }

    /**
     * Create an instance of {@link ApplicantInfo }
     * 
     */
    public ApplicantInfo createApplicantInfo() {
        return new ApplicantInfo();
    }

    /**
     * Create an instance of {@link ResultsTable }
     * 
     */
    public ResultsTable createResultsTable() {
        return new ResultsTable();
    }

    /**
     * Create an instance of {@link StrategyOutcome }
     * 
     */
    public StrategyOutcome createStrategyOutcome() {
        return new StrategyOutcome();
    }

    /**
     * Create an instance of {@link CoApplicantInfo }
     * 
     */
    public CoApplicantInfo createCoApplicantInfo() {
        return new CoApplicantInfo();
    }

    /**
     * Create an instance of {@link ARFFiles }
     * 
     */
    public ARFFiles createARFFiles() {
        return new ARFFiles();
    }

    /**
     * Create an instance of {@link DecisionOutcome }
     * 
     */
    public DecisionOutcome createDecisionOutcome() {
        return new DecisionOutcome();
    }

    /**
     * Create an instance of {@link ScorecardsOutcome }
     * 
     */
    public ScorecardsOutcome createScorecardsOutcome() {
        return new ScorecardsOutcome();
    }

    /**
     * Create an instance of {@link DecisionEngineEval }
     * 
     */
    public DecisionEngineEval createDecisionEngineEval() {
        return new DecisionEngineEval();
    }

    /**
     * Create an instance of {@link ResponseCoApplicantInfo }
     * 
     */
    public ResponseCoApplicantInfo createResponseCoApplicantInfo() {
        return new ResponseCoApplicantInfo();
    }

    /**
     * Create an instance of {@link SMApplicationOutcomes }
     * 
     */
    public SMApplicationOutcomes createSMApplicationOutcomes() {
        return new SMApplicationOutcomes();
    }

    /**
     * Create an instance of {@link SMOutcomes }
     * 
     */
    public SMOutcomes createSMOutcomes() {
        return new SMOutcomes();
    }

    /**
     * Create an instance of {@link SMDataInfo }
     * 
     */
    public SMDataInfo createSMDataInfo() {
        return new SMDataInfo();
    }

    /**
     * Create an instance of {@link ApplicantBureauInfo }
     * 
     */
    public ApplicantBureauInfo createApplicantBureauInfo() {
        return new ApplicantBureauInfo();
    }

    /**
     * Create an instance of {@link CollateralInfo }
     * 
     */
    public CollateralInfo createCollateralInfo() {
        return new CollateralInfo();
    }

    /**
     * Create an instance of {@link FaultDetail }
     * 
     */
    public FaultDetail createFaultDetail() {
        return new FaultDetail();
    }

    /**
     * Create an instance of {@link FinancialInfo }
     * 
     */
    public FinancialInfo createFinancialInfo() {
        return new FinancialInfo();
    }

    /**
     * Create an instance of {@link ApplicantBureauData }
     * 
     */
    public ApplicantBureauData createApplicantBureauData() {
        return new ApplicantBureauData();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DecisionEngineEvalRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://migration.com/soapservice/entity", name = "DecisionEngineEvalRequest")
    public JAXBElement<DecisionEngineEvalRequest> createDecisionEngineEvalRequest(DecisionEngineEvalRequest value) {
        return new JAXBElement<DecisionEngineEvalRequest>(_DecisionEngineEvalRequest_QNAME, DecisionEngineEvalRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Fault }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://migration.com/soapservice/entity", name = "Fault")
    public JAXBElement<Fault> createFault(Fault value) {
        return new JAXBElement<Fault>(_Fault_QNAME, Fault.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DecisionEngineEvalResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://migration.com/soapservice/entity", name = "DecisionEngineEvalResponse")
    public JAXBElement<DecisionEngineEvalResponse> createDecisionEngineEvalResponse(DecisionEngineEvalResponse value) {
        return new JAXBElement<DecisionEngineEvalResponse>(_DecisionEngineEvalResponse_QNAME, DecisionEngineEvalResponse.class, null, value);
    }

}
