//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.19 at 04:10:08 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://migration.com/soapservice/entity", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.migration.soapservice.entity;
