//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.19 at 04:10:08 PM IST 
//


package com.migration.soapservice.entity;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ScorecardsOutcome complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ScorecardsOutcome">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RnkAdvReasonCd" maxOccurs="4" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="StandardOutcomes" type="{http://migration.com/soapservice/entity}StrategyOutcome" minOccurs="0"/>
 *         &lt;element name="ScorecardOutcome" type="{http://migration.com/soapservice/entity}ScorecardOutcome" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ScorecardsOutcome", propOrder = {
    "rnkAdvReasonCd",
    "standardOutcomes",
    "scorecardOutcome"
})
public class ScorecardsOutcome {

    @XmlElement(name = "RnkAdvReasonCd")
    protected List<String> rnkAdvReasonCd;
    @XmlElement(name = "StandardOutcomes")
    protected StrategyOutcome standardOutcomes;
    @XmlElement(name = "ScorecardOutcome")
    protected ScorecardOutcome scorecardOutcome;

    /**
     * Gets the value of the rnkAdvReasonCd property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rnkAdvReasonCd property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRnkAdvReasonCd().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getRnkAdvReasonCd() {
        if (rnkAdvReasonCd == null) {
            rnkAdvReasonCd = new ArrayList<String>();
        }
        return this.rnkAdvReasonCd;
    }

    /**
     * Gets the value of the standardOutcomes property.
     * 
     * @return
     *     possible object is
     *     {@link StrategyOutcome }
     *     
     */
    public StrategyOutcome getStandardOutcomes() {
        return standardOutcomes;
    }

    /**
     * Sets the value of the standardOutcomes property.
     * 
     * @param value
     *     allowed object is
     *     {@link StrategyOutcome }
     *     
     */
    public void setStandardOutcomes(StrategyOutcome value) {
        this.standardOutcomes = value;
    }

    /**
     * Gets the value of the scorecardOutcome property.
     * 
     * @return
     *     possible object is
     *     {@link ScorecardOutcome }
     *     
     */
    public ScorecardOutcome getScorecardOutcome() {
        return scorecardOutcome;
    }

    /**
     * Sets the value of the scorecardOutcome property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScorecardOutcome }
     *     
     */
    public void setScorecardOutcome(ScorecardOutcome value) {
        this.scorecardOutcome = value;
    }

}
