//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.19 at 04:10:08 PM IST 
//


package com.migration.soapservice.entity;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SMApplicationOutcomes complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SMApplicationOutcomes">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RiskScore" type="{http://migration.com/soapservice/entity}ScorecardsOutcome" minOccurs="0"/>
 *         &lt;element name="Pmt" type="{http://migration.com/soapservice/entity}StrategyTableOutcome" minOccurs="0"/>
 *         &lt;element name="XGrade" type="{http://migration.com/soapservice/entity}DataOutcome" minOccurs="0"/>
 *         &lt;element name="CreditRisk" type="{http://migration.com/soapservice/entity}DataOutcome" minOccurs="0"/>
 *         &lt;element name="FinalDecision" type="{http://migration.com/soapservice/entity}DecisionCategoriesOutcome" minOccurs="0"/>
 *         &lt;element name="AdverseAction" type="{http://migration.com/soapservice/entity}DecisionOutcome" minOccurs="0"/>
 *         &lt;element name="MultiAppRiskScore" type="{http://migration.com/soapservice/entity}ScorecardsOutcome" minOccurs="0"/>
 *         &lt;element name="MultiAppPmt" type="{http://migration.com/soapservice/entity}StrategyTableOutcome" minOccurs="0"/>
 *         &lt;element name="MultiAppXGrade" type="{http://migration.com/soapservice/entity}DataOutcome" minOccurs="0"/>
 *         &lt;element name="MultiAppCreditRisk" type="{http://migration.com/soapservice/entity}DataOutcome" minOccurs="0"/>
 *         &lt;element name="MultiAppFinancialInfo" type="{http://migration.com/soapservice/entity}MultiAppFinancialInfo" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SMApplicationOutcomes", propOrder = {
    "riskScore",
    "pmt",
    "xGrade",
    "creditRisk",
    "finalDecision",
    "adverseAction",
    "multiAppRiskScore",
    "multiAppPmt",
    "multiAppXGrade",
    "multiAppCreditRisk",
    "multiAppFinancialInfo"
})
public class SMApplicationOutcomes {

    @XmlElement(name = "RiskScore")
    protected ScorecardsOutcome riskScore;
    @XmlElement(name = "Pmt")
    protected StrategyTableOutcome pmt;
    @XmlElement(name = "XGrade")
    protected DataOutcome xGrade;
    @XmlElement(name = "CreditRisk")
    protected DataOutcome creditRisk;
    @XmlElement(name = "FinalDecision")
    protected DecisionCategoriesOutcome finalDecision;
    @XmlElement(name = "AdverseAction")
    protected DecisionOutcome adverseAction;
    @XmlElement(name = "MultiAppRiskScore")
    protected ScorecardsOutcome multiAppRiskScore;
    @XmlElement(name = "MultiAppPmt")
    protected StrategyTableOutcome multiAppPmt;
    @XmlElement(name = "MultiAppXGrade")
    protected DataOutcome multiAppXGrade;
    @XmlElement(name = "MultiAppCreditRisk")
    protected DataOutcome multiAppCreditRisk;
    @XmlElement(name = "MultiAppFinancialInfo")
    protected MultiAppFinancialInfo multiAppFinancialInfo;

    /**
     * Gets the value of the riskScore property.
     * 
     * @return
     *     possible object is
     *     {@link ScorecardsOutcome }
     *     
     */
    public ScorecardsOutcome getRiskScore() {
        return riskScore;
    }

    /**
     * Sets the value of the riskScore property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScorecardsOutcome }
     *     
     */
    public void setRiskScore(ScorecardsOutcome value) {
        this.riskScore = value;
    }

    /**
     * Gets the value of the pmt property.
     * 
     * @return
     *     possible object is
     *     {@link StrategyTableOutcome }
     *     
     */
    public StrategyTableOutcome getPmt() {
        return pmt;
    }

    /**
     * Sets the value of the pmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link StrategyTableOutcome }
     *     
     */
    public void setPmt(StrategyTableOutcome value) {
        this.pmt = value;
    }

    /**
     * Gets the value of the xGrade property.
     * 
     * @return
     *     possible object is
     *     {@link DataOutcome }
     *     
     */
    public DataOutcome getXGrade() {
        return xGrade;
    }

    /**
     * Sets the value of the xGrade property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataOutcome }
     *     
     */
    public void setXGrade(DataOutcome value) {
        this.xGrade = value;
    }

    /**
     * Gets the value of the creditRisk property.
     * 
     * @return
     *     possible object is
     *     {@link DataOutcome }
     *     
     */
    public DataOutcome getCreditRisk() {
        return creditRisk;
    }

    /**
     * Sets the value of the creditRisk property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataOutcome }
     *     
     */
    public void setCreditRisk(DataOutcome value) {
        this.creditRisk = value;
    }

    /**
     * Gets the value of the finalDecision property.
     * 
     * @return
     *     possible object is
     *     {@link DecisionCategoriesOutcome }
     *     
     */
    public DecisionCategoriesOutcome getFinalDecision() {
        return finalDecision;
    }

    /**
     * Sets the value of the finalDecision property.
     * 
     * @param value
     *     allowed object is
     *     {@link DecisionCategoriesOutcome }
     *     
     */
    public void setFinalDecision(DecisionCategoriesOutcome value) {
        this.finalDecision = value;
    }

    /**
     * Gets the value of the adverseAction property.
     * 
     * @return
     *     possible object is
     *     {@link DecisionOutcome }
     *     
     */
    public DecisionOutcome getAdverseAction() {
        return adverseAction;
    }

    /**
     * Sets the value of the adverseAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link DecisionOutcome }
     *     
     */
    public void setAdverseAction(DecisionOutcome value) {
        this.adverseAction = value;
    }

    /**
     * Gets the value of the multiAppRiskScore property.
     * 
     * @return
     *     possible object is
     *     {@link ScorecardsOutcome }
     *     
     */
    public ScorecardsOutcome getMultiAppRiskScore() {
        return multiAppRiskScore;
    }

    /**
     * Sets the value of the multiAppRiskScore property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScorecardsOutcome }
     *     
     */
    public void setMultiAppRiskScore(ScorecardsOutcome value) {
        this.multiAppRiskScore = value;
    }

    /**
     * Gets the value of the multiAppPmt property.
     * 
     * @return
     *     possible object is
     *     {@link StrategyTableOutcome }
     *     
     */
    public StrategyTableOutcome getMultiAppPmt() {
        return multiAppPmt;
    }

    /**
     * Sets the value of the multiAppPmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link StrategyTableOutcome }
     *     
     */
    public void setMultiAppPmt(StrategyTableOutcome value) {
        this.multiAppPmt = value;
    }

    /**
     * Gets the value of the multiAppXGrade property.
     * 
     * @return
     *     possible object is
     *     {@link DataOutcome }
     *     
     */
    public DataOutcome getMultiAppXGrade() {
        return multiAppXGrade;
    }

    /**
     * Sets the value of the multiAppXGrade property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataOutcome }
     *     
     */
    public void setMultiAppXGrade(DataOutcome value) {
        this.multiAppXGrade = value;
    }

    /**
     * Gets the value of the multiAppCreditRisk property.
     * 
     * @return
     *     possible object is
     *     {@link DataOutcome }
     *     
     */
    public DataOutcome getMultiAppCreditRisk() {
        return multiAppCreditRisk;
    }

    /**
     * Sets the value of the multiAppCreditRisk property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataOutcome }
     *     
     */
    public void setMultiAppCreditRisk(DataOutcome value) {
        this.multiAppCreditRisk = value;
    }

    /**
     * Gets the value of the multiAppFinancialInfo property.
     * 
     * @return
     *     possible object is
     *     {@link MultiAppFinancialInfo }
     *     
     */
    public MultiAppFinancialInfo getMultiAppFinancialInfo() {
        return multiAppFinancialInfo;
    }

    /**
     * Sets the value of the multiAppFinancialInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link MultiAppFinancialInfo }
     *     
     */
    public void setMultiAppFinancialInfo(MultiAppFinancialInfo value) {
        this.multiAppFinancialInfo = value;
    }

}
