//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.19 at 04:10:08 PM IST 
//


package com.migration.soapservice.entity;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SMOutcomes complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SMOutcomes">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AppNbr" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;totalDigits value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PrevPctAdvanced" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="5"/>
 *               &lt;fractionDigits value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PrevMSRP" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="8"/>
 *               &lt;fractionDigits value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PrevEstDealerCost" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="8"/>
 *               &lt;fractionDigits value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PrevPIR" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="5"/>
 *               &lt;fractionDigits value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PrevAppTerm" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;totalDigits value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PrevPaymentProbability" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;totalDigits value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PrevAmountFinanced" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="8"/>
 *               &lt;fractionDigits value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PrevAppTotalIncome" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="8"/>
 *               &lt;fractionDigits value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="AppTotalIncome" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="8"/>
 *               &lt;fractionDigits value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PrevProductType" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PrevAppNbr" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;totalDigits value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PrevFinalDecisionDecCategory" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PrevDealerNumber" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="MonthlyPayment" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="8"/>
 *               &lt;fractionDigits value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="SMDataInfo" type="{http://migration.com/soapservice/entity}SMDataInfo" minOccurs="0"/>
 *         &lt;element name="SMApplicationOutcomes" type="{http://migration.com/soapservice/entity}SMApplicationOutcomes" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SMOutcomes", propOrder = {
    "appNbr",
    "prevPctAdvanced",
    "prevMSRP",
    "prevEstDealerCost",
    "prevPIR",
    "prevAppTerm",
    "prevPaymentProbability",
    "prevAmountFinanced",
    "prevAppTotalIncome",
    "appTotalIncome",
    "prevProductType",
    "prevAppNbr",
    "prevFinalDecisionDecCategory",
    "prevDealerNumber",
    "monthlyPayment",
    "smDataInfo",
    "smApplicationOutcomes"
})
public class SMOutcomes {

    @XmlElement(name = "AppNbr")
    protected BigInteger appNbr;
    @XmlElement(name = "PrevPctAdvanced")
    protected BigDecimal prevPctAdvanced;
    @XmlElement(name = "PrevMSRP")
    protected BigDecimal prevMSRP;
    @XmlElement(name = "PrevEstDealerCost")
    protected BigDecimal prevEstDealerCost;
    @XmlElement(name = "PrevPIR")
    protected BigDecimal prevPIR;
    @XmlElement(name = "PrevAppTerm")
    protected BigInteger prevAppTerm;
    @XmlElement(name = "PrevPaymentProbability")
    protected BigInteger prevPaymentProbability;
    @XmlElement(name = "PrevAmountFinanced")
    protected BigDecimal prevAmountFinanced;
    @XmlElement(name = "PrevAppTotalIncome")
    protected BigDecimal prevAppTotalIncome;
    @XmlElement(name = "AppTotalIncome")
    protected BigDecimal appTotalIncome;
    @XmlElement(name = "PrevProductType")
    protected String prevProductType;
    @XmlElement(name = "PrevAppNbr")
    protected BigInteger prevAppNbr;
    @XmlElement(name = "PrevFinalDecisionDecCategory")
    protected String prevFinalDecisionDecCategory;
    @XmlElement(name = "PrevDealerNumber")
    protected String prevDealerNumber;
    @XmlElement(name = "MonthlyPayment")
    protected BigDecimal monthlyPayment;
    @XmlElement(name = "SMDataInfo")
    protected SMDataInfo smDataInfo;
    @XmlElement(name = "SMApplicationOutcomes")
    protected SMApplicationOutcomes smApplicationOutcomes;

    /**
     * Gets the value of the appNbr property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAppNbr() {
        return appNbr;
    }

    /**
     * Sets the value of the appNbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAppNbr(BigInteger value) {
        this.appNbr = value;
    }

    /**
     * Gets the value of the prevPctAdvanced property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPrevPctAdvanced() {
        return prevPctAdvanced;
    }

    /**
     * Sets the value of the prevPctAdvanced property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPrevPctAdvanced(BigDecimal value) {
        this.prevPctAdvanced = value;
    }

    /**
     * Gets the value of the prevMSRP property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPrevMSRP() {
        return prevMSRP;
    }

    /**
     * Sets the value of the prevMSRP property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPrevMSRP(BigDecimal value) {
        this.prevMSRP = value;
    }

    /**
     * Gets the value of the prevEstDealerCost property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPrevEstDealerCost() {
        return prevEstDealerCost;
    }

    /**
     * Sets the value of the prevEstDealerCost property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPrevEstDealerCost(BigDecimal value) {
        this.prevEstDealerCost = value;
    }

    /**
     * Gets the value of the prevPIR property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPrevPIR() {
        return prevPIR;
    }

    /**
     * Sets the value of the prevPIR property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPrevPIR(BigDecimal value) {
        this.prevPIR = value;
    }

    /**
     * Gets the value of the prevAppTerm property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPrevAppTerm() {
        return prevAppTerm;
    }

    /**
     * Sets the value of the prevAppTerm property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPrevAppTerm(BigInteger value) {
        this.prevAppTerm = value;
    }

    /**
     * Gets the value of the prevPaymentProbability property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPrevPaymentProbability() {
        return prevPaymentProbability;
    }

    /**
     * Sets the value of the prevPaymentProbability property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPrevPaymentProbability(BigInteger value) {
        this.prevPaymentProbability = value;
    }

    /**
     * Gets the value of the prevAmountFinanced property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPrevAmountFinanced() {
        return prevAmountFinanced;
    }

    /**
     * Sets the value of the prevAmountFinanced property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPrevAmountFinanced(BigDecimal value) {
        this.prevAmountFinanced = value;
    }

    /**
     * Gets the value of the prevAppTotalIncome property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPrevAppTotalIncome() {
        return prevAppTotalIncome;
    }

    /**
     * Sets the value of the prevAppTotalIncome property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPrevAppTotalIncome(BigDecimal value) {
        this.prevAppTotalIncome = value;
    }

    /**
     * Gets the value of the appTotalIncome property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAppTotalIncome() {
        return appTotalIncome;
    }

    /**
     * Sets the value of the appTotalIncome property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAppTotalIncome(BigDecimal value) {
        this.appTotalIncome = value;
    }

    /**
     * Gets the value of the prevProductType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrevProductType() {
        return prevProductType;
    }

    /**
     * Sets the value of the prevProductType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrevProductType(String value) {
        this.prevProductType = value;
    }

    /**
     * Gets the value of the prevAppNbr property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPrevAppNbr() {
        return prevAppNbr;
    }

    /**
     * Sets the value of the prevAppNbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPrevAppNbr(BigInteger value) {
        this.prevAppNbr = value;
    }

    /**
     * Gets the value of the prevFinalDecisionDecCategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrevFinalDecisionDecCategory() {
        return prevFinalDecisionDecCategory;
    }

    /**
     * Sets the value of the prevFinalDecisionDecCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrevFinalDecisionDecCategory(String value) {
        this.prevFinalDecisionDecCategory = value;
    }

    /**
     * Gets the value of the prevDealerNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrevDealerNumber() {
        return prevDealerNumber;
    }

    /**
     * Sets the value of the prevDealerNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrevDealerNumber(String value) {
        this.prevDealerNumber = value;
    }

    /**
     * Gets the value of the monthlyPayment property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMonthlyPayment() {
        return monthlyPayment;
    }

    /**
     * Sets the value of the monthlyPayment property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMonthlyPayment(BigDecimal value) {
        this.monthlyPayment = value;
    }

    /**
     * Gets the value of the smDataInfo property.
     * 
     * @return
     *     possible object is
     *     {@link SMDataInfo }
     *     
     */
    public SMDataInfo getSMDataInfo() {
        return smDataInfo;
    }

    /**
     * Sets the value of the smDataInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link SMDataInfo }
     *     
     */
    public void setSMDataInfo(SMDataInfo value) {
        this.smDataInfo = value;
    }

    /**
     * Gets the value of the smApplicationOutcomes property.
     * 
     * @return
     *     possible object is
     *     {@link SMApplicationOutcomes }
     *     
     */
    public SMApplicationOutcomes getSMApplicationOutcomes() {
        return smApplicationOutcomes;
    }

    /**
     * Sets the value of the smApplicationOutcomes property.
     * 
     * @param value
     *     allowed object is
     *     {@link SMApplicationOutcomes }
     *     
     */
    public void setSMApplicationOutcomes(SMApplicationOutcomes value) {
        this.smApplicationOutcomes = value;
    }

}
